# Generated by Django 5.2.7 on 2025-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_record", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="sale",
            name="quantity_sold",
            field=models.BigIntegerField(default=0),
        ),
    ]
