# Generated by Django 5.2.7 on 2025-10-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sales_record",
            "0002_alter_product_quantity_alter_product_selling_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="quantity_sold",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
