# Generated by Django 5.2.7 on 2025-10-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_record", "0005_remove_sale_product_remove_sale_quantity_sold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
